apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-scaledobject
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-deployment
  pollingInterval: 1   # Optional. Default: 30 seconds
  cooldownPeriod: 5    # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
    - type: postgresql
      metadata:
        host: {{ .Values.postgres.host }}
        dbName: {{ .Values.postgres.db }}
        userName: {{ .Values.postgres.username }}
        port: "{{ .Values.postgres.port }}"
        query: "SELECT COUNT(*) FROM {{ .Values.postgres.queueTable }}"
        targetQueryValue: "5"
        activationTargetQueryValue: "0"
        sslmode: disable
      authenticationRef:
        name: postgres-trigger-authentication