CREATE TABLE message_queue (
    id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE ROLE consumer WITH LOGIN SUPERUSER PASSWORD 'pass';

CREATE ROLE keda WITH LOGIN SUPERUSER PASSWORD 'pass';

CREATE ROLE producer WITH LOGIN SUPERUSER PASSWORD 'pass';
